{
  sudo: "required",
  dist: "trusty",
  addons: {
    apt: {
      sources: ["google-chrome"],
      packages: ["google-chrome-stable"]
    }
  },
  language: "node_js",
  node_js: ["10.9"],
  cache: {
    directories: ["node_modules"]
  },
  install: [
    "yarn install"
  ]
}
